<!DOCTYPE html>
<!-- saved from url=(0028)<?= __PABLIC__."myadmin"?>/ -->
<html lang="zh_CN" dir="ltr" class="chrome chrome63"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta name="referrer" content="no-referrer"><meta name="robots" content="noindex,nofollow"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><link rel="icon" href="<?= __PABLIC__."myadmin"?>/favicon.ico" type="image/x-icon"><link rel="shortcut icon" href="<?= __PABLIC__."myadmin"?>/favicon.ico" type="image/x-icon"><link rel="stylesheet" type="text/css" href="<?= __PABLIC__."myadmin"?>/jquery-ui-1.11.4.css"><link rel="stylesheet" type="text/css" href="<?= __PABLIC__."myadmin"?>/codemirror.css"><link rel="stylesheet" type="text/css" href="<?= __PABLIC__."myadmin"?>/show-hint.css"><link rel="stylesheet" type="text/css" href="<?= __PABLIC__."myadmin"?>/lint.css"><link rel="stylesheet" type="text/css" href="<?=__PABLIC__."myadmin"?>/dl.css"><link rel="stylesheet" type="text/css" href="<?= __PABLIC__."myadmin"?>/printview.css" media="print" id="printcss"><title>phpMyAdmin</title><script data-cfasync="false" type="text/javascript" src="<?= __PABLIC__."myadmin"?>/whitelist.php"></script><script data-cfasync="false" type="text/javascript" src="<?= __PABLIC__."myadmin"?>/get_scripts.js.php"></script><script data-cfasync="false" type="text/javascript" src="<?= __PABLIC__."myadmin"?>/get_scripts.js(1).php"></script><script data-cfasync="false" type="text/javascript" src="<?= __PABLIC__."myadmin"?>/get_scripts.js(2).php"></script><script data-cfasync="false" type="text/javascript" src="<?= __PABLIC__."myadmin"?>/get_scripts.js(3).php"></script><script data-cfasync="false" type="text/javascript" src="<?= __PABLIC__."myadmin"?>/messages.php"></script><script data-cfasync="false" type="text/javascript" src="<?= __PABLIC__."myadmin"?>/get_image.js.php"></script><script data-cfasync="false" type="text/javascript">// <![CDATA[
        PMA_commonParams.setAll({common_query:"?lang=zh_CN&collation_connection=utf8_unicode_ci&token=5489ad4cc47f5870cbec2329116aff7e",opendb_url:"db_structure.php",safari_browser:"0",collation_connection:"utf8_unicode_ci",lang:"zh_CN",server:"1",table:"",db:"",token:"5489ad4cc47f5870cbec2329116aff7e",text_dir:"ltr",show_databases_navigation_as_tree:"1",pma_text_default_tab:"浏览",pma_text_left_default_tab:"结构",pma_text_left_default_tab2:"",LimitChars:"50",pftext:"",confirm:"1",LoginCookieValidity:"1440",logged_in:"",PMA_VERSION:"4.6.4",auth_type:"cookie"});
        ConsoleEnterExecutes=false
        AJAX.scriptHandler.add("jquery/jquery-2.1.4.min.js",0).add("whitelist.php?lang=zh_CN&amp;db=&amp;collation_connection=utf8_unicode_ci&amp;token=5489ad4cc47f5870cbec2329116aff7e",1).add("sprintf.js",1).add("ajax.js",0).add("keyhandler.js",1).add("jquery/jquery-ui-1.11.4.min.js",0).add("jquery/jquery.cookie.js",0).add("jquery/jquery.mousewheel.js",0).add("jquery/jquery.event.drag-2.2.js",0).add("jquery/jquery-ui-timepicker-addon.js",0).add("jquery/jquery.ba-hashchange-1.3.js",0).add("jquery/jquery.debounce-1.0.5.js",0).add("menu-resizer.js",1).add("cross_framing_protection.js",0).add("rte.js",1).add("tracekit/tracekit.js",1).add("error_report.js",1).add("messages.php?lang=zh_CN&amp;db=&amp;collation_connection=utf8_unicode_ci&amp;token=5489ad4cc47f5870cbec2329116aff7e",0).add("get_image.js.php?theme=pmahomme",0).add("config.js",1).add("doclinks.js",1).add("functions.js",1).add("navigation.js",1).add("indexes.js",1).add("common.js",1).add("page_settings.js",1).add("codemirror/lib/codemirror.js",0).add("codemirror/mode/sql/sql.js",0).add("codemirror/addon/runmode/runmode.js",0).add("codemirror/addon/hint/show-hint.js",0).add("codemirror/addon/hint/sql-hint.js",0).add("codemirror/addon/lint/lint.js",0).add("codemirror/addon/lint/sql-lint.js",0).add("console.js",1);
        $(function() {AJAX.fireOnload("whitelist.php?lang=zh_CN&amp;db=&amp;collation_connection=utf8_unicode_ci&amp;token=5489ad4cc47f5870cbec2329116aff7e");AJAX.fireOnload("sprintf.js");AJAX.fireOnload("keyhandler.js");AJAX.fireOnload("menu-resizer.js");AJAX.fireOnload("rte.js");AJAX.fireOnload("tracekit/tracekit.js");AJAX.fireOnload("error_report.js");AJAX.fireOnload("config.js");AJAX.fireOnload("doclinks.js");AJAX.fireOnload("functions.js");AJAX.fireOnload("navigation.js");AJAX.fireOnload("indexes.js");AJAX.fireOnload("common.js");AJAX.fireOnload("page_settings.js");AJAX.fireOnload("console.js");});
        // ]]></script><noscript>&lt;style&gt;html{display:block}&lt;/style&gt;</noscript></head><body id="loginform"><div id="page_content">
    <div class="container">
        <a href="<?= __PABLIC__."myadmin"?>/url.php?url=https%3A%2F%2Fwww.phpmyadmin.net%2F" target="_blank" class="logo"><img src="<?= __PABLIC__."myadmin"?>/logo_right.png" id="imLogo" name="imLogo" alt="phpMyAdmin" border="0"></a>
        <h1>欢迎使用 <bdo dir="ltr" lang="en">phpMyAdmin</bdo></h1><noscript>
            &lt;div class="error"&gt;&lt;img src="themes/dot.gif" title="" alt="" class="icon ic_s_error" /&gt; 该处必须启用 Javascript！&lt;/div&gt;</noscript>
        <div class="hide js-show" style="display: block;"><form method="get" action="<?= __PABLIC__."myadmin"?>/index.php" class="disableAjax"><input type="hidden" name="db" value=""><input type="hidden" name="table" value=""><input type="hidden" name="lang" value="zh_CN"><input type="hidden" name="collation_connection" value="utf8_unicode_ci"><input type="hidden" name="token" value="5489ad4cc47f5870cbec2329116aff7e"><fieldset><legend lang="en" dir="ltr">语言 - <em>Language</em></legend><select name="lang" class="autosubmit" lang="en" dir="ltr" id="sel-lang"><option value="hy">Հայերէն - Armenian</option><option value="az">Azərbaycanca - Azerbaijani</option><option value="bn">বাংলা - Bangla</option><option value="pt_br">Português - Brazilian Portuguese</option><option value="bg">Български - Bulgarian</option><option value="ca">Català - Catalan</option><option value="zh_cn" selected="selected">中文 - Chinese simplified</option><option value="zh_tw">中文 - Chinese traditional</option><option value="cs">Čeština - Czech</option><option value="da">Dansk - Danish</option><option value="nl">Nederlands - Dutch</option><option value="en">English</option><option value="en_gb">English (United Kingdom)</option><option value="et">Eesti - Estonian</option><option value="fi">Suomi - Finnish</option><option value="fr">Français - French</option><option value="gl">Galego - Galician</option><option value="de">Deutsch - German</option><option value="el">Ελληνικά - Greek</option><option value="hu">Magyar - Hungarian</option><option value="id">Bahasa Indonesia - Indonesian</option><option value="ia">Interlingua</option><option value="it">Italiano - Italian</option><option value="ja">日本語 - Japanese</option><option value="ko">한국어 - Korean</option><option value="lt">Lietuvių - Lithuanian</option><option value="nb">Norsk - Norwegian</option><option value="pl">Polski - Polish</option><option value="pt">Português - Portuguese</option><option value="ro">Română - Romanian</option><option value="ru">Русский - Russian</option><option value="sr@latin">Srpski - Serbian (latin)</option><option value="si">සිංහල - Sinhala</option><option value="sq">Shqip - Slbanian</option><option value="sk">Slovenčina - Slovak</option><option value="sl">Slovenščina - Slovenian</option><option value="es">Español - Spanish</option><option value="sv">Svenska - Swedish</option><option value="tr">Türkçe - Turkish</option><option value="uk">Українська - Ukrainian</option><option value="vi">Tiếng Việt - Vietnamese</option></select></fieldset></form></div>
        <br>
        <!-- Login form -->
        <form method="post" action="./gologin" name="login_form" class="disableAjax login hide js-show" style="display: inline;">
            <fieldset>
                <legend>登录<a href="<?= __PABLIC__."myadmin"?>" target="documentation"><img src="<?= __PABLIC__."myadmin"?>/dot.gif" title="文档" alt="文档" class="icon ic_b_help"></a></legend><div class="item">
                    <label for="input_username">用户名：</label>
                    <input type="text" name="pma_username" id="input_username" value="" size="24" class="textfield">
                </div>
                <div class="item">
                    <label for="input_password">密码：</label>
                    <input type="password" name="pma_password" id="input_password" value="" size="24" class="textfield">
                </div>    <input type="hidden" name="server" value="1"></fieldset>
            <fieldset class="tblFooters">
                <input value="执行" type="submit" id="input_go"><input type="hidden" name="target" value="index.php"><input type="hidden" name="lang" value="zh_CN"><input type="hidden" name="collation_connection" value="utf8_unicode_ci"><input type="hidden" name="token" value="5489ad4cc47f5870cbec2329116aff7e"></fieldset>
        </form></div></div></body></html>